role :blog, "23.21.68.153"
set :user, "ubuntu"
set :blog_location, "/home/ubuntu/blog"

desc "Copies the static blog generated by jekyll to the server."
task :copy_blog_to_server do
  upload("/Users/muffs/Projects/hangry/_site", "#{blog_location}", :via => :scp, :recursive => true)
end

desc "Moves the blog up one directory to be semantically correct."
task :relocate_blog_up_one_directory do
  run "mv #{blog_location}/_site/* #{blog_location}"
end

desc "Delete old location of the blog."
task :relocate_blog_up_one_directory do
  run "rm -rf #{blog_location}/_site"
end
